export const COLORS = {
  white: "#FFF",
  black: "#000",
  bgColor: "#FF0",
  redPlayerColor: "#F00",
  redFieldBorder: "#FA4B4B",
  redField: "#FFEFEF",
  yellowPlayerColor: "#DBBA23",
  yellowFieldBorder: "#DBBA23",
  yellowField: "#FFD",
  greenPlayerColor: "#27CF27",
  greenFieldBorder: "#27CF27",
  greenField: "#DFD",
  bluePlayerColor: "#00F",
  blueFieldBorder: "#4E4EF5",
  blueField: "#DDF",
};
